name: kalm
channels:
  - defaults
show_channel_urls: true
dependencies:
  - python=3.10.6
  - pip:
    - datasets==2.20.0
    - deepspeed==0.12.6
    - FlagEmbedding==1.1
    - faiss-gpu==1.7.2
    - huggingface-hub==0.23.2
    - mteb==1.14.5
    - peft==0.8.2
    - sentence-transformers==3.3.1
    - torch==2.0.1
    - tqdm==4.66.3
    - transformers==4.45.2
    